# -*- coding: utf-8 -*-
"""HousePricePrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z2UK5n6I7Z7OEwKMC2fl5tvvfK6W9veu

## HOUSE PRICE PREDICTION USING LINEAR REGRESSION
"""

#Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Impoerting the Datasets
df = pd.read_csv("House-Price-Prediction-clean.csv")
df.drop(['Id'],axis=1,inplace=True)
df

#Assigning the x and y variables
x = df.iloc[:, :-1].values
y = df.iloc[:,-1].values

#splitting the datasets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15,random_state=10000)

#Linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
#Predicting the accuracy score
score=r2_score(y_test,y_pred)
print(score)

#Polotting the Linear Regression
plt.scatter(y_test,y_pred)
plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')
plt.title('House Price Prediction')
m,b=np.polyfit(y_test,y_pred,1)
plt.plot(y_test,m*y_test+b,color='red')
plt.legend(['Actual vs Predicted','Reression Line'])
plt.show()

#Printing Actual vs Predicted values
pd.DataFrame({'actual':y_test,'predict':y_pred})